# 5. pod 의 재시작 정책 설정
# 6. spec 을 쉽게 확인하는 방법
apiVersion: v1
kind: Pod
metadata:
  name: my-simple-pod
spec:
  #restartPolicy:
  containers:
    - name: my-container
      image: nginx:1.24
# 5. pod 의 재시작 정책 설정
#    - defalut 는 always.
#      지금처럼 restartPolicy 를 선언하지 않으면 됨.
#
#    - 이러한 선언적인 spec 가 잘 모르겠다면,
#      kubectl explain pod
#      kubectl explain pod.spec
#      검색결과에서 선언하려고 하는 spec 을 찾으면 됨.
#
# 6. spec 을 쉽게 확인하는 방법
#    - kubectl explain pod
#      조회된 내용중에서 fields 항목에서 원하는 spec 을 찾음.
#    - kubectl explain pod.spec
#      조회된 내용중에서 restartPolicy filed 를 찾음.
#      사용가능 값이 Always, Never, OnFailure  확인.

#      상세한 내용을 확인할 수 있는 웹페이지 url 도 있음.
