apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-150
spec:
  storageClassName: host-pv #PVC에서 스토리지 사용 요청시 사용하는 정보
  persistentVolumeReclaimPolicy: Delete # PVC 삭제 -> PV 데이터도 삭제
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteMany # multi PV 가 접속해서 사용
  hostPath:
    path: "/my-pv/data/pv1"
# kubectl apply -f ex10-my-pv-150.yaml
