# K8S 의 Downward API 사용 예제

# ex5-1-env.yaml 코드를 추가 확장해서 실습 진행.
apiVersion: v1
kind: Pod
metadata:
  name: env-test-pod
spec:
  containers:
    - name: my-container
      image: nginx
      # 컨테이너 전용 환경변수 설정
      env:
        # 환경변수 1. 설정
        - name: SAMPLE_ENV # 환경 변수명
          value: "Sample Variable"
          # 환경변수 2 설정
          # POD_NAME 환경 변수는 pod 의 이름(env-test-pod)을 컨테이너 내부에 설정
        - name: POD_NAME
          # 참조해서 사용할 수 있도록, value 대신에 valueFrom 으로 정의함.
          valueFrom:
            fieldRef:
              # meta.name 처럼 참조를 위한 field 를 지정하는 것을
              # K8S 에서는 , downward api 라고 함.
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

