# ConfigMap, secret 를 pod 에서 참조해서 사용하는 실습예제.

apiVersion: v1
kind: Pod
metadata:
  name: my-config-secret-pod
spec:
  containers:
    - name: my-container
      image:
        nginx
        # 컨테이너에서 사용할 환경변수 설정
      env:
        # 환경변수 1 (ConfigMap 참조)
        # configMap 을 참조해서 환경 변수 1 을 초기화
        - name: DB_HOST
          # secret 객체 참조
          valueFrom:
            configMapKeyRef:
              name: my-config # ConfigMap 이름
              # my-config 의 key 중에서 db_host key 를 참조
              key: db_host # ConfigMap 안의 key 값
              # db_host 의 value 를 참조해서 DB_HOST 를 초기화
        # 환경변수 2 (Secret 참조)
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret # Secret 이름
              key: DB_PW # Secret 안의 key 값
