# 서로 다른 Pod 에 있는 컨테이너 간 호출

apiVersion: v1
kind: Service
metadata:
  # name : 외부에서 이 서비스를 호출하는 기준이 됨.
  #        외부에서 my-service 라는 이름으로 호출하게 됨.
  name: my-service
spec:
  # ClusterIP 는 default. 생략이 가능함.
  # 하지만, 명시적으로 작성하는 것이 좋음.
  type: ClusterIP
  # selector : 이 서비스의 대상이 되는 Pod 들을 지정.
  #            그리고, my-service 호출로 실제로 호출되는 Pod 들은
  #            endpointslices 객체가 가지고 있음.
  selector:
    # ex2-1-my-nginx-deploy.yaml 에서 작성한
    # Deployment 의 Pod 들이 대상이 됨.
    # Deployment 의 selector 와 동일한 selector 을 지정.
    app: my-nginx
  ports:
    # nginx 컨테이너의 내부 80 port 가 my-service 의 9080 port 로 매핑됨
    - protocol: TCP
      # Service 는 9080 port 을 호출되도록 지정
      port: 9080
      # Deployment 의 Pod 들은 nginx 임으로 80 port 를 지정
      targetPort: 80
#
#
# kubectl apply -f ex2-2-my-service.yaml
#
# kubectl get service
#
# ENDPOINTS 항목에 표시된 IP 목록을 확인 => 3개 를 확인.
# kubectl get endpointslices
#
# kubectl get pods
#
# ENDPOINTS 항목에 표시된 IP 를 Pod 에서 확인
# kubectl describe pod my-nginx-deploy-8474f7bd66-6vw8t => 10.244.0.10
#
# pod 간의 컨테이너 호출
# my-localhost-pod(nginx) -> my-service:9080 -> my-nginx-deploy(nginx)
#
# kubectl exec my-localhost-pod -c nginx-container -- curl my-service:9080
