logging:
  file:
    name: logs/api.log
  level:
    root: info
    org.msa.gatewayserver: debug
  logback:
    rolling policy:
      max-file-size: 500MB
      max-history: 10

spring:
  cloud:
    gateway:
      # routes 는 클라이언트의 요청 URI 에 대해서
      # 어떤 마이크로 서비스로 요청을 전달해야 할것인지와 같은
      # 라우팅 관련정보를 설정
      routes:
        # id 는 라우팅을 위한 식별 id 임.
        - id: item-service
          # uri 는 이동할 마이크로서비스 명임.
          # lb 는 load balancing 의 약자임.
          # item-service 는 유레카 서버에 등록된 마이크로 서비스 명임.
          uri: lb://item-service
          #predicates 의 Path 설정은 실제 요청이 들어온 , uri 주소임.
          # v1/item/ 으로 시작하는 요청이 들어왔을 때,
          # item-service 마이크로 서비스로 요청을 전달하겠다는 의미임.
          predicates:
            - Path=/v1/item/**



 # Eureka Server 에 자기자신(item-service)을 등록
eureka:
  instance:
    # prefer-ip-address 는 hostname 이 아닌 ip 주소를 이용해서
    # 유레카 서버에 등록할 것인지 여부를 설정.
    # true : ip 주소를 이용해서 등록하겠다는 설정.
    prefer-ip-address: true
  client:
    #register-with-eureka 는 마이크로 서비스를 유레카 서버 레지스트리에 등록 할 것인지 여부.
    # 현재 yaml 은 item-service 임으로 유레카 서버 레지스트리에 등록이 필요함으로 true 로 설정.
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: http://localhost:8761/eureka



