apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-factorial-app
  namespace: factorial
spec:
  replicas: 2
  ################# 02.업데이트 전략 추가 - start ###################
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0


  ################# 02.업데이트 전략 추가 - end  ###################
  selector:
    matchLabels:
      app: factorial-app
  template:
    metadata:
      labels:
        app: factorial-app
    spec:
      containers:
        - name: factorial
          image: wnsgud0310/factorial-app:0.0.2

# kubectl apply -f factorial-app-deploy2.yaml
# kubectl -n factorial get pods
# kubectl -n factorial describe pod pid-id
